import type { Slate } from "./types";

/**
 * Where the data comes from.
 *
 * index.html loads `./data/slate.js` with a plain <script> tag, which sets
 * window.SLATE. That is deliberate: a page opened by double-click (file://)
 * cannot fetch() a local file, but <script src> is permitted. So the whole
 * primary workflow — grid, card, flags, optimizer — runs with no server.
 *
 * sql.js against data/golf.db (Phase 3) DOES need fetch(), which is why the
 * Results Browser is the one thing that goes dark on file://. `servedOverHttp`
 * is what that tab keys off.
 */

export type SlateStatus =
  | { ok: true; slate: Slate }
  | { ok: false; reason: "missing" | "malformed"; detail: string };

export function loadSlate(): SlateStatus {
  const s = window.SLATE;

  if (!s) {
    return {
      ok: false,
      reason: "missing",
      detail:
        "data/slate.js did not load. Run the notebook's Export cell to generate it.",
    };
  }

  // Shape-check rather than trust: slate.js is generated by Python and is not
  // covered by the TypeScript build, so `Slate` is an assertion about a file
  // the compiler never sees. Catch a bad export here, where the message can
  // name the problem, instead of downstream as a render crash.
  if (!Array.isArray(s.players) || !s.meta) {
    return {
      ok: false,
      reason: "malformed",
      detail: "window.SLATE is present but has no meta/players.",
    };
  }
  if (s.players.length === 0) {
    return {
      ok: false,
      reason: "malformed",
      detail: "window.SLATE.players is empty — the field did not export.",
    };
  }

  return { ok: true, slate: s };
}

/** False when opened from disk. Gates anything that needs fetch(). */
export const servedOverHttp = window.location.protocol.startsWith("http");
