# utils/dashboard.py
# Publishes the weekly slate for the PGA Slate Terminal (dashboard/).
#
# Why a .js file and not .json/.csv: a page opened by double-click (file://)
# cannot fetch() a local file, but a <script src> tag is permitted. Writing
# `window.SLATE = {...}` means the grid, player card, flags and optimizer all
# work with no server running. Only sql.js against golf.db needs a server, so
# only the Results Browser goes dark on file://.
#
# Why this is computed in Python rather than in the browser: there are no IDs
# anywhere in the schema — every join is on player-name strings reconciled
# through data/name_mappings.json. A JS-side join would silently drop players
# whose names differ between DK and the PGA feed, and the failure is invisible
# (a player just quietly has no course history). Computing here also guarantees
# the card's numbers come from the same code that trains the model, which is
# what stops "100% cuts made" appearing above "CUTS /20 95%".
#
# The contract this writes is typed in dashboard/src/types.ts. Renaming a key
# here without changing that file is a compile error there, by design.

import json
import os
import shutil
from datetime import datetime, timezone

import numpy as np
import pandas as pd
from sqlalchemy import create_engine

from utils.features import (load_tables, build_rounds, current_streak,
                            sg_features_for_event, sg_at_course_for_event,
                            SG_HALFLIFE_DAYS)

# Vite serves public/ in dev and dist/ in a build, so there is no single
# location both modes read. These are the only two copies that exist; both are
# gitignored and regenerated by the notebook.
DASHBOARD_DIR = "dashboard"
PUBLIC_DATA = os.path.join(DASHBOARD_DIR, "public", "data")
DIST_DATA = os.path.join(DASHBOARD_DIR, "dist", "data")
SLATE_FILENAME = "slate.js"

# Mirrors utils.model.CURRENT_WEEK_META. Duplicated rather than imported so
# `python -m utils.dashboard` does not pull in sklearn just to read a path.
CURRENT_WEEK_META = "data/current_week.json"

# ONE lineup file, overwritten in place, living in OneDrive.
#
# Not one file per week: a running archive of every week's lineups is clutter
# nobody reads, and it would grow forever. The file carries the tournament and
# date it belongs to, so a stale one is simply ignored by the app and silently
# overwritten when the new week's lineups are built.
#
# It sits in OneDrive rather than the repo so it syncs between computers on its
# own. In the repo it was tracked, which meant a commit and a pull every time
# lineups moved, and a dirty working tree every time the dashboard was merely
# opened. OneDrive does that transport in the background for free.
#
# %OneDrive% is set by Windows to that machine's own OneDrive root, so the same
# expression resolves correctly under a different username on another computer.
# That matters: the built dashboard is identical on both machines and never
# learns the path — it talks to LINEUP_ENDPOINT and the local server resolves it.
LINEUP_SUBPATH = os.path.join("Fantasy Golf", "Lineup_Optimizer")
LINEUP_DIR_FALLBACK = "data/lineups"   # no OneDrive: keep working, local only
LINEUP_FILENAME = "current.json"
LINEUP_ENDPOINT = "/api/lineups"


def resolve_lineup_dir(explicit: str | None = None) -> str:
    """Where current.json lives on THIS machine, most specific source first.

        1. an explicit argument      (serve_dashboard(lineup_dir=...), --lineup-dir)
        2. $PGA_LINEUP_DIR           (per-machine override, if OneDrive moves)
        3. %OneDrive%/Fantasy Golf/Lineup_Optimizer
        4. data/lineups              (no OneDrive on this machine)

    Returned as an absolute path so the server's log line is unambiguous about
    which of the four it landed on.
    """
    if explicit:
        return os.path.abspath(os.path.expanduser(explicit))
    env = os.environ.get("PGA_LINEUP_DIR")
    if env:
        return os.path.abspath(os.path.expanduser(env))
    onedrive = os.environ.get("OneDrive") or os.environ.get("OneDriveConsumer")
    if onedrive and os.path.isdir(onedrive):
        return os.path.abspath(os.path.join(onedrive, LINEUP_SUBPATH))
    return os.path.abspath(LINEUP_DIR_FALLBACK)

DK_CAP = 50000
DK_ROSTER = 6


def _json_safe(obj):
    """numpy scalars and NaN are not JSON-serialisable. NaN becomes null so the
    TS side sees `number | null` rather than a literal NaN token, which is not
    valid JSON and would fail to parse."""
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        f = float(obj)
        return None if np.isnan(f) else f
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, pd.Timestamp):
        return str(obj.date())
    raise TypeError(f"not JSON-serialisable: {type(obj)}")


def _players_payload(export_df: pd.DataFrame) -> list:
    """export_df verbatim — the same 14 columns as current_week_export.csv.

    Deliberately not re-derived: the CSV and the dashboard must show identical
    numbers, so they come from one frame. Sorted by P_TOP20 descending to match
    the CSV's order, though the UI sorts client-side anyway."""
    df = export_df.copy()
    if "P_TOP20" in df.columns:
        df = df.sort_values("P_TOP20", ascending=False)
    # NaN -> None per column; .to_dict() would otherwise emit float('nan').
    return json.loads(df.to_json(orient="records", double_precision=6))


def _current_owgr(db_path: str, season: int, players: list) -> dict:
    """Current-season world ranking, name -> rank (or None).

    The OWGR_RANK that arrives in export_df is a MODEL FEATURE: it comes from
    the training season's stats, because that is the only ranking the model is
    allowed to see when predicting. For reading a board on Sunday night that is
    the wrong number — Cameron Young was 19th last season and is 3rd now.

    So the dashboard overlays this week's ranking on top, from the same `stats`
    table and same season as the SG-by-phase card. Display only: export_df, the
    CSV and the predictions log keep the model's value, so nothing that is
    scored or graded moves.

    Players with no current-season row get None rather than falling back to the
    training value — a column that silently mixed two seasons would be worse
    than one with a few blanks in it.
    """
    engine = create_engine(f"sqlite:///{db_path}")
    with engine.begin() as conn:
        owgr = pd.read_sql(
            "SELECT PLAYER, OWGR_RANK FROM stats WHERE SEASON = ?",
            conn, params=(int(season),))
    engine.dispose()

    owgr = owgr.drop_duplicates(subset="PLAYER").set_index("PLAYER")["OWGR_RANK"]
    out = {}
    for name in players:
        v = owgr.get(name)
        out[name] = None if v is None or pd.isna(v) else int(v)
    return out


def serve_dashboard(port: int = 8765, open_browser: bool = True,
                    root: str = ".", block: bool = False,
                    lineup_dir: str | None = None) -> str:
    """Serve the repo root and open the dashboard.

    `lineup_dir` overrides where current.json is read and written. Leave it
    None for the normal case — see resolve_lineup_dir() for what that picks.

    `block=False` (the notebook's case) runs the server on a daemon thread and
    returns, so the cell finishes and the server lives as long as the kernel.

    `block=True` (run.bat's case) runs it in the foreground and does not
    return, so a standalone process stays alive without a notebook. That is the
    difference between the two ways in: a daemon thread dies with its process,
    which is correct for a kernel and useless for a double-click.

    Rooted at the REPO, not at dashboard/dist, because the Results Browser
    fetches data/golf.db in place — the 20 MB file is already tracked in git and
    copying it into dashboard/ every week would add a 20 MB blob to history each
    time.

    Idempotent: re-running the cell reuses the already-running server rather
    than failing on a bound port, so the notebook can be run end to end
    repeatedly in one session.
    """
    import functools
    import http.server
    import socket
    import socketserver
    import threading
    import webbrowser

    url = f"http://localhost:{port}/dashboard/dist/index.html"

    lineups_dir = resolve_lineup_dir(lineup_dir)
    lineup_file = os.path.join(lineups_dir, LINEUP_FILENAME)

    class _Handler(http.server.SimpleHTTPRequestHandler):
        """Static files, plus GET and POST on LINEUP_ENDPOINT for lineups.

        The write path lives here rather than in the browser because every
        browser-side option is worse: the File System Access API is
        Chromium-only and re-prompts each session, and a GitHub token embedded
        in the page would be readable by anyone the moment the page is hosted.
        A localhost server the notebook already starts has none of those
        problems.

        The READ is an endpoint rather than a static file because the lineup
        file lives in OneDrive, outside the served root. Going through the
        server is also what keeps the built page machine-independent: it asks
        for a fixed relative URL and never knows the path behind it.
        """

        def _send_json(self, obj, code=200):
            body = json.dumps(obj).encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            # The whole point is picking up another machine's edits; a cached
            # response would defeat it.
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):  # noqa: N802 - name fixed by BaseHTTPRequestHandler
            # Split off the cache-busting query the client appends.
            if self.path.split("?", 1)[0] != LINEUP_ENDPOINT:
                return super().do_GET()
            try:
                with open(lineup_file, encoding="utf-8") as f:
                    self._send_json(json.load(f))
            except FileNotFoundError:
                # No lineups saved yet — normal on a new machine or a new week.
                self.send_error(404, "no lineup file yet")
            except (OSError, json.JSONDecodeError) as e:
                # A half-synced or corrupt file must not wedge the dashboard;
                # the browser falls back to its localStorage copy on any error.
                self.send_error(500, f"unreadable lineup file: {e}")

        def do_POST(self):  # noqa: N802 - name fixed by BaseHTTPRequestHandler
            if self.path != LINEUP_ENDPOINT:
                self.send_error(404)
                return
            try:
                length = int(self.headers.get("Content-Length", 0))
            except ValueError:
                self.send_error(400, "bad Content-Length")
                return
            # The payload is names and ids — a few KB at most. The cap stops a
            # runaway client from filling memory, nothing more.
            if length <= 0 or length > 1_000_000:
                self.send_error(413, "payload too large")
                return

            raw = self.rfile.read(length)
            try:
                state = json.loads(raw.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError) as e:
                self.send_error(400, f"not JSON: {e}")
                return
            if not isinstance(state, dict) or "tournament" not in state:
                self.send_error(400, "missing tournament")
                return

            try:
                # Fixed destination: the path never comes from the request, so
                # there is nothing to traverse out of.
                os.makedirs(lineups_dir, exist_ok=True)
                tmp = lineup_file + ".tmp"
                with open(tmp, "w", encoding="utf-8") as f:
                    json.dump(state, f, indent=2)
                # Atomic, so OneDrive never uploads a half-written file and the
                # other machine never reads one.
                os.replace(tmp, lineup_file)
            except OSError as e:
                self.send_error(500, str(e))
                return

            self._send_json({"ok": True, "path": lineup_file})

        def log_message(self, *args):
            # Silent: an autosave every few seconds would bury the notebook's
            # own output under request logs.
            pass

    def _in_use() -> bool:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            return s.connect_ex(("127.0.0.1", port)) == 0

    if not os.path.exists(os.path.join(DASHBOARD_DIR, "dist", "index.html")):
        print("⚠️ dashboard/dist not built. Run `npm install && npm run build` in dashboard/.")
        return url

    if _in_use():
        # Another instance already holds the port — the notebook's server, or a
        # run.bat window left open. Point the browser at it rather than failing.
        # No lineup path is printed: the running server has its own, and this
        # call's lineups_dir is not the one that will be used.
        print(f"ℹ️ Server already running on port {port} — reusing it.")
        print(f"   {url}")
        if open_browser:
            webbrowser.open(url)
        return url

    handler = functools.partial(_Handler, directory=os.path.abspath(root))

    class _Quiet(socketserver.ThreadingTCPServer):
        allow_reuse_address = True
        daemon_threads = True

        def handle_error(self, request, client_address):
            # A browser cancelling a 20 MB golf.db fetch mid-flight raises
            # ConnectionAbortedError here. It is normal and would otherwise
            # dump a traceback into the notebook output every reload.
            pass

    httpd = _Quiet(("127.0.0.1", port), handler)
    print(f"✅ Serving {os.path.abspath(root)} on port {port}")
    print(f"   {url}")
    # Printed every launch on purpose: this is the one setting that differs
    # between the two computers, and a silently wrong path would look exactly
    # like lineups vanishing.
    print(f"📁 Lineups: {lineup_file}")
    if not os.path.isdir(lineups_dir):
        print("   (folder does not exist yet — it is created on the first save)")

    if not block:
        threading.Thread(target=httpd.serve_forever, daemon=True).start()
        if open_browser:
            webbrowser.open(url)
        return url

    # Foreground. Open the browser slightly late so the first request cannot
    # arrive before serve_forever() is listening.
    if open_browser:
        threading.Timer(0.6, webbrowser.open, [url]).start()
    print("   Close this window (or Ctrl+C) to stop the server.")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n🛑 Server stopped.")
    finally:
        httpd.server_close()
    return url


def _phases_payload(db_path: str, season: int, players: list) -> dict:
    """Season strokes-gained by phase, from the `stats` table.

    Driving -> SGOTT, Approach -> SGAPR, Around green -> SGATG, Putting -> SGP.

    Ranks come from the DB's own *_RANK columns, which are PGA-Tour-wide, NOT
    field-relative. The card shows them as an absolute anchor; the percentile
    bars and phase flags rank against THIS week's field and are computed in the
    browser from the values. Two different populations, deliberately.

    Coverage is partial by design — the stats table only carries players with
    enough measured rounds (~68% of a DK field). Missing players get an entry
    of nulls rather than no entry, so the UI never distinguishes "absent key"
    from "no data".
    """
    engine = create_engine(f"sqlite:///{db_path}")
    with engine.begin() as conn:
        stats = pd.read_sql(
            "SELECT PLAYER, SGOTT, SGAPR, SGATG, SGP, SGTTG, "
            "SGOTT_RANK, SGAPR_RANK, SGATG_RANK, SGP_RANK, SGTTG_RANK "
            "FROM stats WHERE SEASON = ?",
            conn, params=(int(season),))
    engine.dispose()

    stats = stats.drop_duplicates(subset="PLAYER").set_index("PLAYER")
    # SGTTG is tee-to-green: the OTT + APP + ARG composite, excluding putting.
    # It is a headline number in its own right, not a fifth phase.
    cols = [("ott", "SGOTT"), ("app", "SGAPR"), ("arg", "SGATG"), ("putt", "SGP"),
            ("ttg", "SGTTG")]

    out = {}
    for name in players:
        row = stats.loc[name] if name in stats.index else None
        phases = {}
        for key, col in cols:
            v = None if row is None else row[col]
            r = None if row is None else row[f"{col}_RANK"]
            phases[key] = None if v is None or pd.isna(v) else round(float(v), 4)
            phases[f"{key}_rank"] = None if r is None or pd.isna(r) else int(r)
        out[name] = {"phases": phases}
    return out


HISTORY_DAYS = 730      # the scatter's 24-month window
RESULTS_LIMIT = 40      # recent-results rows per player
LAST_N_STARTS = 20      # window for cuts/top-20 rate and the streak
VOL_ROUNDS = 40         # ~10 starts: enough rounds for a stable SD
MIN_ROUNDS_FOR_SPREAD = 12   # below this, an SD is noise, so publish nothing
MOMENTUM_DAYS = 90      # how far back the rolling-form line is compared


def _history_payload(t_all: pd.DataFrame, rounds_all: pd.DataFrame,
                     players: list, ending: pd.Timestamp, course: str,
                     ch_present: set) -> dict:
    """Per-player round history, course history and recent results.

    Everything here is derived with the SAME functions that build the model's
    features — build_rounds() for per-round SG, current_streak() for the streak
    — so the card cannot disagree with the model about what it is showing.

    Note this contradicts the design handoff, which claims the only per-event
    quantity in the DB is score and instructs retitling the scatter to "SG per
    event". Per-ROUND SG is real: build_rounds() derives it from ROUNDS:1..4 as
    (that event-round's field mean) minus (the player's score).
    """
    field = set(players)
    # History is strictly before this week — the event being predicted has no
    # results yet, and including it would be lookahead.
    t = t_all[t_all["PLAYER"].isin(field)]
    t = t[t["ENDING_DATE"] < ending]
    all_rounds = rounds_all[rounds_all["PLAYER"].isin(field)]
    all_rounds = all_rounds[all_rounds["ENDING_DATE"] < ending]

    # Per-event SG: the mean of that event's round SGs, over ALL history rather
    # than the scatter's 24-month window. Recent-results rows reach back 40
    # starts and course visits reach back to the player's first appearance, so
    # windowing this would blank the SG column on older rows that do have data.
    ev_sg = (all_rounds.groupby(["PLAYER", "TOURNAMENT", "ENDING_DATE"])["SG"]
             .mean().rename("EV_SG").reset_index())

    # The scatter's window is separate and narrower.
    rounds = all_rounds[all_rounds["ENDING_DATE"] >= ending - pd.Timedelta(days=HISTORY_DAYS)]

    r_by_player = dict(tuple(rounds.sort_values("ENDING_DATE").groupby("PLAYER")))
    t_by_player = dict(tuple(t.groupby("PLAYER")))
    ev_by_player = dict(tuple(ev_sg.groupby("PLAYER")))

    out = {}
    for name in players:
        pr = r_by_player.get(name)
        pt = t_by_player.get(name)

        # --- (e) SG per round, plus the rolling form line ---
        # The trend is an exponentially weighted mean with the model's own
        # 100-day halflife — the same weighting family as SG_FORM, and the same
        # line the Streamlit app draws. It is computed HERE rather than in the
        # browser on purpose: reimplementing pandas' time-based EWMA in JS is
        # exactly the kind of cross-platform port that silently diverges.
        rounds_out = []
        if pr is not None and len(pr):
            # Spread an event's four rounds across four days: round 4 on the
            # ending date, round 1 three days earlier. Off by at most a day for
            # Saturday/Monday finishes. Without this all four rounds share one
            # x-position, which stacks the scatter into vertical columns and
            # turns the trend line into vertical jumps joined by flat steps.
            # Same approximation the Streamlit app uses.
            pr = pr.assign(
                DATE=pr["ENDING_DATE"] - pd.to_timedelta(4 - pr["RND"], unit="D")
            ).sort_values("DATE")
            ser = pr.set_index("DATE")["SG"]
            trend = ser.ewm(halflife=pd.Timedelta(days=SG_HALFLIFE_DAYS),
                            times=ser.index).mean()
            for (d, sg), tv in zip(ser.items(), trend.values):
                rounds_out.append([str(pd.Timestamp(d).date()),
                                   round(float(sg), 2), round(float(tv), 3)])

        rounds_12m = 0
        if pr is not None and len(pr):
            rounds_12m = int((pr["ENDING_DATE"] >= ending - pd.Timedelta(days=365)).sum())

        # --- (f) two things the rest of the card cannot show ---
        #
        # Both are computed here rather than in the browser for the same reason
        # the trend line is: they must be derived from the same round frame the
        # scatter draws, with one definition, not re-derived in JS.
        #
        # volatility: SD of per-round SG over the last VOL_ROUNDS rounds. This
        # is the round-to-round spread, which is the floor/ceiling axis and is
        # deliberately NOT scored as good or bad — high spread is what you want
        # in a GPP and what you avoid in cash. Measured against SG_FORM at
        # r = -0.25 across this field, so it is close to independent of level.
        #
        # momentum: how much the rolling-form line has moved over the last
        # MOMENTUM_DAYS. SG_FORM is a level; this is its direction, and nothing
        # else on the card states it as a number. r = 0.17 with SG_FORM and
        # 0.05 with ceiling — the least redundant thing available.
        volatility = momentum = None
        if pr is not None and len(pr) >= MIN_ROUNDS_FOR_SPREAD:
            sg = pr["SG"].tail(VOL_ROUNDS)
            # ddof=1: this is a sample of the player's rounds, not a population.
            volatility = round(float(sg.std(ddof=1)), 2)

            # The trend series is already indexed by round date. Compare its
            # last value with its value as of MOMENTUM_DAYS earlier. A player
            # who has not teed it up inside the window has no prior point and
            # gets None rather than a fabricated zero.
            past = trend[trend.index <= trend.index[-1]
                         - pd.Timedelta(days=MOMENTUM_DAYS)]
            if len(past):
                momentum = round(float(trend.iloc[-1] - past.iloc[-1]), 2)

        # --- (c) form profile over the last N starts ---
        cuts_20 = top20_20 = None
        streak = None
        if pt is not None and len(pt):
            recent = pt.sort_values("ENDING_DATE", ascending=False)
            head = recent.head(LAST_N_STARTS)
            cuts_20 = round(float((~head["POS"].isin(["CUT", "W/D"])).mean()) * 100, 0)
            top20_20 = round(float((head["FINAL_POS"] <= 20).mean()) * 100, 0)
            run, kind = current_streak(recent["POS"])
            streak = [int(run), kind] if kind else None

        # --- (g) course history AT THIS WEEK'S COURSE ONLY ---
        # The card is a this-week view, so a scrolling list of every venue the
        # player has ever seen is noise. What matters is depth on the one course
        # being played: how many events, how they finished, and each visit.
        # Other venues live in the Course tab and the Results Browser.
        here = None
        course_events = []
        if pt is not None and len(pt):
            cc = pt[pt["COURSE"] == course]
            if len(cc):
                here = {
                    "ev": int(cc["FINAL_POS"].count()),
                    "avg": round(float(cc["FINAL_POS"].mean()), 1),
                    "best": int(cc["FINAL_POS"].min()),
                    # Percent BEFORE rounding: a frame-wide round(1) on the
                    # fraction quantizes this to the nearest 10%.
                    "cut_pct": int(round(
                        float((~cc["POS"].isin(["CUT", "W/D"])).mean()) * 100)),
                }
                evs = ev_by_player.get(name)
                sg_here = {}
                if evs is not None:
                    sg_here = {(r.TOURNAMENT, r.ENDING_DATE): r.EV_SG
                               for r in evs.itertuples(index=False)}
                for row in cc.sort_values("ENDING_DATE", ascending=False).itertuples(index=False):
                    sg = sg_here.get((row.TOURNAMENT, row.ENDING_DATE))
                    course_events.append({
                        "date": str(pd.Timestamp(row.ENDING_DATE).date()),
                        "tournament": row.TOURNAMENT,
                        "finish": str(row.POS),
                        "sg": None if sg is None or pd.isna(sg) else round(float(sg), 2),
                    })

        # --- (h) recent results ---
        results = []
        if pt is not None and len(pt):
            evs = ev_by_player.get(name)
            sg_lookup = {}
            if evs is not None:
                sg_lookup = {(r.TOURNAMENT, r.ENDING_DATE): r.EV_SG
                             for r in evs.itertuples(index=False)}
            recent = pt.sort_values("ENDING_DATE", ascending=False).head(RESULTS_LIMIT)
            for row in recent.itertuples(index=False):
                sg = sg_lookup.get((row.TOURNAMENT, row.ENDING_DATE))
                results.append({
                    "date": str(pd.Timestamp(row.ENDING_DATE).date()),
                    "tournament": row.TOURNAMENT,
                    "finish": str(row.POS),
                    "sg": None if sg is None or pd.isna(sg) else round(float(sg), 2),
                })

        out[name] = {
            "rounds_12m": rounds_12m,
            "cuts_20": cuts_20,
            "top20_20": top20_20,
            "streak": streak,
            "volatility": volatility,
            "momentum": momentum,
            "rounds": rounds_out,
            "course_here": here,
            "course_events": course_events,
            # Whether SG_CH_SHRUNK is a REAL measurement for this player, i.e.
            # they have rounds at this course inside the model's 7-year window.
            #
            # This cannot be inferred from the exported value being 0. The CSV
            # rounds to 2 decimals, and a player who performed at exactly field
            # average rounds to 0.0 — Beau Hossler is -0.0045 over 6 events at
            # Detroit. An absent player is ALSO 0 (NaN filled). Treating 0 as
            # "no history" mislabels the genuinely-average players, so presence
            # is published explicitly instead.
            "ch_window": name in ch_present,
            "results": results,
        }
    return out


SG_TREND_DAYS = 30          # lookback for the SG-rankings rank movement
SG_SPARK_ROUNDS = 20
COURSE_MIN_ROUNDS = 4       # floor for appearing in the course table at all


def _sg_rankings_payload(rounds: pd.DataFrame, ending: pd.Timestamp) -> list:
    """SG form for EVERY active player, with rank movement and a sparkline.

    This is the Streamlit app's "SG Rankings" view. It is deliberately NOT
    restricted to this week's DK field — the point of the view is to see who is
    playing well across the whole tour, including players not in this field.

    SG_FORM comes from sg_features_for_event(), the same function that builds
    the model's feature, so the numbers reconcile with the export.
    """
    now = sg_features_for_event(rounds, ending)
    if now.empty:
        return []
    now = now.sort_values("SG_FORM", ascending=False).reset_index(drop=True)
    now["RANK"] = np.arange(1, len(now) + 1)

    prev = sg_features_for_event(rounds, ending - pd.Timedelta(days=SG_TREND_DAYS))
    if not prev.empty:
        prev = prev.sort_values("SG_FORM", ascending=False).reset_index(drop=True)
        prev["PREV_RANK"] = np.arange(1, len(prev) + 1)
        now = now.merge(prev[["PLAYER", "PREV_RANK"]], on="PLAYER", how="left")
    else:
        now["PREV_RANK"] = np.nan

    recent = rounds[rounds["ENDING_DATE"] >= ending - pd.Timedelta(days=HISTORY_DAYS)]
    spark = (recent.sort_values("ENDING_DATE").groupby("PLAYER")["SG"]
             .apply(lambda x: [round(float(v), 2) for v in x.tail(SG_SPARK_ROUNDS)]))

    out = []
    for row in now.itertuples(index=False):
        move = None
        if pd.notna(row.PREV_RANK):
            move = int(row.PREV_RANK - row.RANK)   # positive = climbed
        out.append({
            "rank": int(row.RANK),
            "player": row.PLAYER,
            "sg_form": round(float(row.SG_FORM), 4),
            "rounds_12m": int(row.SG_ROUNDS_12M),
            "move": move,
            "spark": spark.get(row.PLAYER, []),
        })
    return out


def _course_payload(t: pd.DataFrame, rounds: pd.DataFrame, course: str,
                    ending: pd.Timestamp, model_sg: pd.DataFrame) -> dict:
    """Horses for courses at THIS week's venue, measured in strokes.

    Only this week's course is precomputed. Every course would be ~20k rows and
    roughly double the payload, and the model's SG_CH_SHRUNK is a shrunk
    7-year window that would have to be reimplemented in SQL to compute other
    courses in the browser — exactly the kind of port that silently disagrees
    with the feature the model was actually trained on. Other venues remain
    reachable through the Results Browser.

    SG (model) is sg_at_course_for_event() itself, so this table reconciles
    with SG_CH_SHRUNK in the export. SG (raw) is the plain unshrunk mean, for
    intuition about sample size.
    """
    sub_t = t[(t["COURSE"] == course) & (t["ENDING_DATE"] < ending)]
    sub_r = rounds[(rounds["COURSE"] == course) & (rounds["ENDING_DATE"] < ending)]
    if sub_t.empty:
        return {"course": course, "events": 0, "first_year": None,
                "last_year": None, "players": []}

    res = (sub_t.groupby("PLAYER")
           .agg(events=("FINAL_POS", "count"),
                best=("FINAL_POS", "min"),
                avg_finish_pct=("FINISH_PCT", "mean"),
                cuts=("POS", lambda x: (~x.isin(["CUT", "W/D"])).mean()),
                last_played=("ENDING_DATE", "max")))

    sg = (sub_r.groupby("PLAYER")
          .agg(course_rounds=("SG", "count"), sg_raw=("SG", "mean")))

    ce = res.join(sg, how="inner").reset_index().merge(model_sg, on="PLAYER", how="left")
    ce = ce[ce["course_rounds"] >= COURSE_MIN_ROUNDS]
    ce = ce.sort_values("SG_CH_SHRUNK", ascending=False)

    players = []
    for row in ce.itertuples(index=False):
        players.append({
            "player": row.PLAYER,
            "sg_model": None if pd.isna(row.SG_CH_SHRUNK) else round(float(row.SG_CH_SHRUNK), 3),
            "sg_raw": round(float(row.sg_raw), 3),
            "rounds": int(row.course_rounds),
            "events": int(row.events),
            "avg_finish_pct": round(float(row.avg_finish_pct), 3),
            "cut_pct": int(round(float(row.cuts) * 100)),
            "best": int(row.best),
            "last_played": int(pd.Timestamp(row.last_played).year),
        })

    evs = sub_t[["TOURNAMENT", "ENDING_DATE"]].drop_duplicates()
    return {
        "course": course,
        "events": int(len(evs)),
        "first_year": int(sub_t["ENDING_DATE"].min().year),
        "last_year": int(sub_t["ENDING_DATE"].max().year),
        "players": players,
    }


TOP_N = 15


def _weeks_payload(j: pd.DataFrame) -> list:
    """Per-week track record: of the model's 15 highest P_TOP20, how many
    finished top-20, and their cut rate. Baseline is 6.49 hits, from the
    forward-chained eval in experiments/forward_eval.py.

    Uses the SAME pandas nlargest() call as utils.model.grade_predictions()
    rather than re-selecting the top 15 in a hand-rolled sort. That is not
    fussiness: P_TOP20 is rounded to 3 decimals when logged, so ties at the
    15-player boundary are common (the 2026 3M Open had a three-way tie at
    0.301), and two different tie-breaks silently disagree about the cut rate.
    One selection, one answer, in both views.
    """
    out = []
    for (tourn, date), grp in j.groupby(["TOURNAMENT", "ENDING_DATE"]):
        graded = grp["FINAL_POS"].notna().any()
        top15 = grp.nlargest(TOP_N, "P_TOP20")
        out.append({
            "date": str(pd.Timestamp(date).date()),
            "tournament": tourn,
            "players": int(len(grp)),
            "graded": bool(graded),
            "expected": round(float(top15["P_TOP20"].sum()), 1),
            "hits": int((top15["FINAL_POS"] <= 20).sum()) if graded else None,
            # Read from POS, not inferred from FINAL_POS: 90 is the DB's fill
            # value for CUT/WD, so a numeric threshold would conflate a genuine
            # 90th-place finish with a missed cut. Same test Streamlit uses.
            "cut_rate": (int(round(100 * float(
                (~top15["POS"].isin(["CUT", "W/D"])).mean())))
                if graded else None),
        })
    return sorted(out, key=lambda w: w["date"], reverse=True)


def _tracker_payload(db_path: str):
    """Logged predictions joined to actual finishes, for the Prediction Tracker.

    The join is (TOURNAMENT, ENDING_DATE, PLAYER) — there are no event or player
    IDs in this schema. The design handoff's stub SQL assumed event_id/player_id
    and a p_top20_pred column; none of those exist. This mirrors the join in
    utils.model.grade_predictions().

    Returns (rows, joined_frame) — the frame is handed to _weeks_payload() so
    the per-week table and the per-player calibration rows are built from one
    join rather than two.
    """
    engine = create_engine(f"sqlite:///{db_path}")
    with engine.begin() as conn:
        try:
            preds = pd.read_sql(
                "SELECT TOURNAMENT, ENDING_DATE, PLAYER, P_TOP20 FROM predictions", conn)
        except Exception:
            engine.dispose()
            return [], pd.DataFrame()
        results = pd.read_sql(
            "SELECT TOURNAMENT, ENDING_DATE, PLAYER, POS, FINAL_POS FROM tournaments", conn)
    engine.dispose()

    if preds.empty:
        return [], pd.DataFrame()

    j = preds.merge(results, on=["TOURNAMENT", "ENDING_DATE", "PLAYER"], how="left")

    # `j` is returned UNSORTED, in the order read_sql produced. That matters:
    # nlargest() breaks ties by row order, P_TOP20 is logged rounded to 3
    # decimals so boundary ties are common, and grade_predictions() groups the
    # unsorted frame. Sorting here would reshuffle which tied player lands in
    # the top 15 and make this table disagree with the notebook's report card
    # for the same week. Only the display copy below is sorted.
    out = []
    for row in j.sort_values("ENDING_DATE", ascending=False).itertuples(index=False):
        graded = pd.notna(row.FINAL_POS)
        out.append({
            "date": str(pd.Timestamp(row.ENDING_DATE).date()),
            "tournament": row.TOURNAMENT,
            "player": row.PLAYER,
            "p_top20": None if pd.isna(row.P_TOP20) else round(float(row.P_TOP20), 4),
            "finish": int(row.FINAL_POS) if graded else None,
            "pos": None if pd.isna(row.POS) else str(row.POS),
            "hit": bool(row.FINAL_POS <= 20) if graded else None,
        })
    return out, j


def export_dashboard(db_path: str, export_df: pd.DataFrame, config: dict,
                     verbose: bool = True) -> dict:
    """Write dashboard/public/data/slate.js (and mirror into dist/ if built).

    Publishes meta, the scored field, season SG-by-phase, per-player round /
    course / results history, and the graded prediction log.
    """
    new = config["new"]
    ending = pd.Timestamp(new["ending_date"])

    players = _players_payload(export_df)
    names = [p["PLAYER"] for p in players]

    # Replace the model's (training-season) world ranking with this season's.
    # See _current_owgr: the board is for reading, not for scoring.
    owgr_now = _current_owgr(db_path, int(new["season"]), names)
    for p in players:
        p["OWGR_RANK"] = owgr_now[p["PLAYER"]]

    # Loaded once and shared: build_rounds() unpivots ~56k tournament rows into
    # ~200k round rows, and three of the payloads below need it.
    t_all, _s, _o = load_tables(db_path)
    rounds_all = build_rounds(t_all)

    # Computed once and shared. Presence in this frame — not a rounded zero in
    # the CSV — is what tells the UI whether SG_CH_SHRUNK is a real measurement.
    model_sg = sg_at_course_for_event(rounds_all, ending, new["course"])
    ch_present = set(model_sg["PLAYER"])

    form = _phases_payload(db_path, int(new["season"]), names)
    history = _history_payload(t_all, rounds_all, names, ending, new["course"], ch_present)
    for name in names:
        form[name].update(history.get(name, {}))

    tracker, tracker_join = _tracker_payload(db_path)
    weeks = _weeks_payload(tracker_join) if len(tracker_join) else []
    sg_rankings = _sg_rankings_payload(rounds_all, ending)
    course = _course_payload(t_all, rounds_all, new["course"], ending, model_sg)

    slate = {
        "meta": {
            "tournament": new["name"],
            "course": new["course"],
            "ending_date": str(ending.date()),
            "season": int(new["season"]),
            "field_size": len(players),
            "generated_at": datetime.now(timezone.utc)
                            .isoformat(timespec="seconds"),
            "cap": DK_CAP,
            "roster": DK_ROSTER,
        },
        "players": players,
        "form": form,
        "tracker": tracker,
        "weeks": weeks,
        "sg_rankings": sg_rankings,
        "course": course,
    }

    payload = json.dumps(slate, default=_json_safe, separators=(",", ":"))
    body = (
        "// Generated by utils/dashboard.py — do not edit.\n"
        "// Regenerated every time the notebook's Export cell runs.\n"
        f"window.SLATE = {payload};\n"
    )

    written = []
    os.makedirs(PUBLIC_DATA, exist_ok=True)
    primary = os.path.join(PUBLIC_DATA, SLATE_FILENAME)
    with open(primary, "w", encoding="utf-8") as f:
        f.write(body)
    written.append(primary)

    # Only mirror into dist/ when a build already exists — creating the folder
    # would fake a built app that cannot actually load.
    if os.path.isdir(os.path.dirname(DIST_DATA)):
        os.makedirs(DIST_DATA, exist_ok=True)
        mirror = os.path.join(DIST_DATA, SLATE_FILENAME)
        shutil.copyfile(primary, mirror)
        written.append(mirror)

    if verbose:
        kb = len(body.encode("utf-8")) / 1024
        with_stats = sum(1 for v in form.values() if v["phases"]["ott"] is not None)
        n_rounds = sum(len(v.get("rounds", [])) for v in form.values())
        graded = sum(1 for r in tracker if r["finish"] is not None)
        print(f"✅ Dashboard slate → {len(players)} players, {kb:.0f} KB")
        with_owgr = sum(1 for p in players if p["OWGR_RANK"] is not None)
        print(f"   {with_stats} with {new['season']} SG stats · "
              f"{with_owgr} with {new['season']} OWGR · {n_rounds:,} rounds · "
              f"{len(tracker)} tracked predictions ({graded} graded)")
        print(f"   SG rankings {len(sg_rankings)} players · "
              f"{course['course']}: {len(course['players'])} players / "
              f"{course['events']} events")
        for p in written:
            print(f"   → {p}")
        if len(written) == 1:
            print("   (dist/ not built yet — run `npm run build` in dashboard/)")

    return slate


def rebuild_from_disk(db_path: str = "data/golf.db",
                      export_csv: str = "data/current_week_export.csv",
                      meta_path: str = CURRENT_WEEK_META) -> dict:
    """Regenerate slate.js from files already on disk, without the notebook.

    slate.js is generated weekly and therefore gitignored, so a fresh clone has
    no data and the dashboard opens empty. Everything needed to rebuild it IS
    tracked — golf.db, the week's export CSV, and the current-week marker — so
    this reconstructs the slate in a couple of seconds with no odds scrape, no
    DraftKings file and no model training.

    That makes a second machine usable immediately after `git clone`, and gives
    a way to re-export after changing this module without re-running the whole
    pipeline.
    """
    with open(meta_path, encoding="utf-8") as f:
        meta = json.load(f)
    config = {"new": {
        "name": meta["name"],
        "course": meta["course"],
        "season": int(meta["season"]),
        "ending_date": pd.Timestamp(meta["ending_date"]),
    }}
    return export_dashboard(db_path, pd.read_csv(export_csv), config)


def slate_is_stale() -> bool:
    """True when slate.js is missing or older than the export it derives from.

    Covers the two cases that matter: a fresh clone (slate.js is gitignored, so
    it is simply absent) and a pull that brought a newer week's export CSV
    without the generated slate.
    """
    for path in (os.path.join(PUBLIC_DATA, SLATE_FILENAME),
                 os.path.join(DIST_DATA, SLATE_FILENAME)):
        if not os.path.exists(path):
            return True
    src = "data/current_week_export.csv"
    if os.path.exists(src):
        newest = max(os.path.getmtime(os.path.join(d, SLATE_FILENAME))
                     for d in (PUBLIC_DATA, DIST_DATA))
        if os.path.getmtime(src) > newest:
            return True
    return False


if __name__ == "__main__":
    import argparse
    import sys

    # A Windows console defaults to cp1252, which cannot encode the checkmarks
    # and arrows in the progress output — the run would die on its first print.
    # Jupyter's stdout is already UTF-8, so this only matters from a terminal.
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):
        pass

    ap = argparse.ArgumentParser(
        prog="python -m utils.dashboard",
        description="Rebuild the dashboard slate, and optionally serve it.")
    ap.add_argument("--serve", action="store_true",
                    help="serve the dashboard and stay running (what run.bat does)")
    ap.add_argument("--port", type=int, default=8765)
    ap.add_argument("--no-browser", action="store_true")
    ap.add_argument("--lineup-dir", default=None,
                    help="folder holding current.json "
                         "(default: %%OneDrive%%/Fantasy Golf/Lineup_Optimizer)")
    args = ap.parse_args()

    if not args.serve:
        rebuild_from_disk()
    else:
        # Only regenerate when it would actually change something — three
        # seconds of needless work on every launch is three seconds of a
        # double-click feeling broken.
        if slate_is_stale():
            print("⏳ Slate missing or out of date — rebuilding…")
            rebuild_from_disk()
        serve_dashboard(port=args.port, open_browser=not args.no_browser,
                        block=True, lineup_dir=args.lineup_dir)
