# utils/dashboard.py
# Publishes the weekly slate for the PGA Slate Terminal (dashboard/).
#
# Why a .js file and not .json/.csv: a page opened by double-click (file://)
# cannot fetch() a local file, but a <script src> tag is permitted. Writing
# `window.SLATE = {...}` means the grid, player card, flags and optimizer all
# work with no server running. Only sql.js against golf.db needs a server, so
# only the Results Browser goes dark on file://.
#
# Why this is computed in Python rather than in the browser: there are no IDs
# anywhere in the schema — every join is on player-name strings reconciled
# through data/name_mappings.json. A JS-side join would silently drop players
# whose names differ between DK and the PGA feed, and the failure is invisible
# (a player just quietly has no course history). Computing here also guarantees
# the card's numbers come from the same code that trains the model, which is
# what stops "100% cuts made" appearing above "CUTS /20 95%".
#
# The contract this writes is typed in dashboard/src/types.ts. Renaming a key
# here without changing that file is a compile error there, by design.

import json
import os
import shutil
from datetime import datetime, timezone

import numpy as np
import pandas as pd
from sqlalchemy import create_engine

# Vite serves public/ in dev and dist/ in a build, so there is no single
# location both modes read. These are the only two copies that exist; both are
# gitignored and regenerated by the notebook.
DASHBOARD_DIR = "dashboard"
PUBLIC_DATA = os.path.join(DASHBOARD_DIR, "public", "data")
DIST_DATA = os.path.join(DASHBOARD_DIR, "dist", "data")
SLATE_FILENAME = "slate.js"

DK_CAP = 50000
DK_ROSTER = 6


def _json_safe(obj):
    """numpy scalars and NaN are not JSON-serialisable. NaN becomes null so the
    TS side sees `number | null` rather than a literal NaN token, which is not
    valid JSON and would fail to parse."""
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        f = float(obj)
        return None if np.isnan(f) else f
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, pd.Timestamp):
        return str(obj.date())
    raise TypeError(f"not JSON-serialisable: {type(obj)}")


def _players_payload(export_df: pd.DataFrame) -> list:
    """export_df verbatim — the same 14 columns as current_week_export.csv.

    Deliberately not re-derived: the CSV and the dashboard must show identical
    numbers, so they come from one frame. Sorted by P_TOP20 descending to match
    the CSV's order, though the UI sorts client-side anyway."""
    df = export_df.copy()
    if "P_TOP20" in df.columns:
        df = df.sort_values("P_TOP20", ascending=False)
    # NaN -> None per column; .to_dict() would otherwise emit float('nan').
    return json.loads(df.to_json(orient="records", double_precision=6))


def _phases_payload(db_path: str, season: int, players: list) -> dict:
    """Season strokes-gained by phase, from the `stats` table.

    Driving -> SGOTT, Approach -> SGAPR, Around green -> SGATG, Putting -> SGP.

    Ranks come from the DB's own *_RANK columns, which are PGA-Tour-wide, NOT
    field-relative. The card shows them as an absolute anchor; the percentile
    bars and phase flags rank against THIS week's field and are computed in the
    browser from the values. Two different populations, deliberately.

    Coverage is partial by design — the stats table only carries players with
    enough measured rounds (~68% of a DK field). Missing players get an entry
    of nulls rather than no entry, so the UI never distinguishes "absent key"
    from "no data".
    """
    engine = create_engine(f"sqlite:///{db_path}")
    with engine.begin() as conn:
        stats = pd.read_sql(
            "SELECT PLAYER, SGOTT, SGAPR, SGATG, SGP, "
            "SGOTT_RANK, SGAPR_RANK, SGATG_RANK, SGP_RANK "
            "FROM stats WHERE SEASON = ?",
            conn, params=(int(season),))
    engine.dispose()

    stats = stats.drop_duplicates(subset="PLAYER").set_index("PLAYER")
    cols = [("ott", "SGOTT"), ("app", "SGAPR"), ("arg", "SGATG"), ("putt", "SGP")]

    out = {}
    for name in players:
        row = stats.loc[name] if name in stats.index else None
        phases = {}
        for key, col in cols:
            v = None if row is None else row[col]
            r = None if row is None else row[f"{col}_RANK"]
            phases[key] = None if v is None or pd.isna(v) else round(float(v), 4)
            phases[f"{key}_rank"] = None if r is None or pd.isna(r) else int(r)
        out[name] = {"phases": phases}
    return out


def export_dashboard(db_path: str, export_df: pd.DataFrame, config: dict,
                     verbose: bool = True) -> dict:
    """Write dashboard/public/data/slate.js (and mirror into dist/ if built).

    Publishes meta + players + season SG-by-phase. Round history, course
    history, recent results and the prediction tracker land in Phase 2;
    `tracker` is emitted as an empty list rather than omitted so the TS shape
    stays stable.
    """
    new = config["new"]
    ending = pd.Timestamp(new["ending_date"])

    players = _players_payload(export_df)
    names = [p["PLAYER"] for p in players]
    form = _phases_payload(db_path, int(new["season"]), names)

    slate = {
        "meta": {
            "tournament": new["name"],
            "course": new["course"],
            "ending_date": str(ending.date()),
            "season": int(new["season"]),
            "field_size": len(players),
            "generated_at": datetime.now(timezone.utc)
                            .isoformat(timespec="seconds"),
            "cap": DK_CAP,
            "roster": DK_ROSTER,
        },
        "players": players,
        "form": form,
        "tracker": [],   # Phase 2
    }

    payload = json.dumps(slate, default=_json_safe, separators=(",", ":"))
    body = (
        "// Generated by utils/dashboard.py — do not edit.\n"
        "// Regenerated every time the notebook's Export cell runs.\n"
        f"window.SLATE = {payload};\n"
    )

    written = []
    os.makedirs(PUBLIC_DATA, exist_ok=True)
    primary = os.path.join(PUBLIC_DATA, SLATE_FILENAME)
    with open(primary, "w", encoding="utf-8") as f:
        f.write(body)
    written.append(primary)

    # Only mirror into dist/ when a build already exists — creating the folder
    # would fake a built app that cannot actually load.
    if os.path.isdir(os.path.dirname(DIST_DATA)):
        os.makedirs(DIST_DATA, exist_ok=True)
        mirror = os.path.join(DIST_DATA, SLATE_FILENAME)
        shutil.copyfile(primary, mirror)
        written.append(mirror)

    if verbose:
        kb = len(body.encode("utf-8")) / 1024
        with_stats = sum(1 for v in form.values() if v["phases"]["ott"] is not None)
        print(f"✅ Dashboard slate → {len(players)} players, {kb:.0f} KB "
              f"({with_stats} with {new['season']} SG stats)")
        for p in written:
            print(f"   → {p}")
        if len(written) == 1:
            print("   (dist/ not built yet — run `npm run build` in dashboard/)")

    return slate
